"""unique friend pairs

Revision ID: 980a2cc28d25
Revises: 18e44a6c713c
Create Date: 2026-01-12 02:31:12.066153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980a2cc28d25'
down_revision = '18e44a6c713c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.drop_index('idx_friend_user_status')
        batch_op.create_unique_constraint('uq_friend_pair', ['user_id', 'friend_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.drop_constraint('uq_friend_pair', type_='unique')
        batch_op.create_index('idx_friend_user_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###
